LGC.Support/Controllers/CalendarController.cs
using LGC.Support.Models;
using LGC.Support.Services;
using Microsoft.AspNetCore.Mvc;
using System;

namespace LGC.Support.Controllers
{
    public class CalendarController : Controller
    {
        private readonly CalendarService _calendar;
        private readonly EmailService _email;

        public CalendarController(CalendarService calendar, EmailService email)
        {
            _calendar = calendar;
            _email = email;
        }

        public IActionResult Index()
        {
            ViewBag.events = _calendar.GetAll().Result;
            return View();
        }

        [HttpPost]
        public IActionResult Index(CalendarData model)
        {

            try
            {
                if (model.id == 0)
                {
                    var created = _calendar.Create(model);
                    TempData["Message"] = "Event Created!";
                    return RedirectToAction("Index");
                }
                else
                {
                    var result = _calendar.Update(model).Result;
                    if (result != null)
                    {
                        TempData["Message"] = "Update Successfully!";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Event not found.";
                        return RedirectToAction("Index");
                    }

                }

            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View(model);
            }

        }


        [HttpPost]
        public IActionResult Delete(CalendarData model)
        {
            try
            {
                var result = _calendar.Delete(model).Result;
                return Json(new { result = "ok" });
            }
            catch (Exception ex)
            {
                return Json(new { result = ex.Message });
            }
        }

    }
}

LGC.Support/Views/Calendar/Index.cshtml
@using Newtonsoft.Json
@model LGC.Support.Models.CalendarData

<div class="row">
    <div class="col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2 style="font-weight: bold">
                    Calendar Events &emsp;
                    <button class="btn-sm btn-dark btn-add-event" tabindex="0" aria-controls="datatable-buttons"><i class="fa fa-plus"> Add</i></button>
                </h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div id="calendar" class="fc fc-unthemed fc-ltr">
                </div>
            </div>
        </div>
    </div>
</div>

<div id="CalenderModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="background-color: #172D44; color: #ffff">
                <h4 class="modal-title" id="myModalLabel">New Calendar</h4>
            </div>
            <div class="modal-body">
                <div id="testmodal" style="padding: 5px 20px;">
                    <form asp-controller="Calendar" asp-action="Index" id="event-modal-form" class="form-horizontal calender" role="form">
                        <div class="item form-group">
                            <label class="col-form-label col-md-3 col-sm-3 label-align">
                                Title 
                            </label>
                            <div class="col-md-9 col-sm-9">
                                <input asp-for="title" type="text" id="event-title" required="required" class="form-control">
                            </div>
                        </div>
                        <div class="item form-group" hidden="hidden" id="event-created_by-form">
                            <label class="col-form-label col-md-3 col-sm-3 label-align">
                                Created by
                            </label>
                            <div class="col-md-9 col-sm-9">
                                <input asp-for="created_by" type="text" id="event-created_by" readonly="readonly" class="form-control">
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="col-form-label col-md-3 col-sm-3 label-align">
                                Date 
                            </label>
                            <div class="col-md-6 col-sm-6">
                                <input asp-for="event_date" id="event-date" class="date-picker form-control" placeholder="dd-mm-yyyy" type="date" required="required" onfocus="this.type='date'" onmouseover="this.type='date'" onclick="this.type='date'" onblur="this.type='text'" onmouseout="timeFunctionLong(this)">
                                <script>
                                    function timeFunctionLong(input) {
                                        setTimeout(function() {
                                            input.type = 'text';
                                        }, 60000);
                                    }
                                </script>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label col-md-3 col-sm-3 label-align">
                                Remind me:
                            </label>
                            <div class="col-md-9 col-sm-9 ">
                                <select asp-for="remind_before_day" class="form-control" id="event-reminder">
                                    <option value="7">7 Days before</option>
                                    <option value="10">10 Days before</option>
                                    <option value="15">15 Days before</option>
                                </select>
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="col-form-label col-md-3 col-sm-3 label-align">
                                Description
                            </label>
                            <div class="col-md-9 col-sm-9">
                                <textarea asp-for="description" id="event-description" class="form-control" rows="3" style="height: 111px;" maxlength=255></textarea>
                            </div>
                        </div>

                        <input hidden name="id" type="text" id="event-id" required="required" class="form-control">

                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary antosubmit btn-save-modal">Save Changes</button>
                            <button hidden="hidden" type="button" class="btn btn-danger btn-delete-modal">Delete</button>
                            <button type="button" class="btn btn-danger antoclose btn-close-modal" data-dismiss="modal">Close</button>
                        </div>
                    </form>

                </div>
            </div>


        </div>
    </div>
</div>


@section Scripts{

<script>

    var events = []
    var events_from_db = @Html.Raw(JsonConvert.SerializeObject(ViewBag.events));



    for (var i = 0; i < events_from_db.length; i++) {
        events.push({
            id: events_from_db[i].id,
            title: events_from_db[i].title,
            start: events_from_db[i].event_date
        });
    }


    $('#calendar').fullCalendar({
        header: {
            left: 'prev,next today',
            center: 'title',
            right: 'month' // ,agendaWeek,agendaDay
        },
        buttonText: {
            today: 'today',
            month: 'month',
            week: 'week',
            day: 'day'
        },
        eventSources: [
            // your event source
            {
                events: events,
                textColor: '#ffff',
                color: '#0C73B2'// an option!
            }
        ],
        dayClick: function (date, jsEvent, view) {
            var today_date = moment().format('YYYY-MM-DD');

            if (date.format('YYYY-MM-DD') > today_date || date.format('YYYY-MM-DD') === today_date) {
                $(".btn-delete-modal").attr("hidden", "hidden");
                $("#event-created_by-form").attr("hidden", "hidden");
                $("#event-date").val(date.format());
                $("#event-reminder").val("7").change();
                $("#CalenderModal").attr("class", "modal fade show");
                $("#CalenderModal").attr("style", "display: block; padding-right: 16px;");
            }
        },

        eventMouseover: function () {
            $(this).css('background-color', '#1C96BA');
        },

        eventMouseout: function () {
            $(this).css('background-color', '#0C73B2');
        },

        eventClick: function (event, element) {

            for (var i = 0; i < events_from_db.length; i++) {

                if (event.id === events_from_db[i].id) {
                    $("#event-title").val(`${events_from_db[i].title}`);
                    $("#event-created_by").val(`${events_from_db[i].created_by}`);
                    $("#event-date").val(`${events_from_db[i].event_date}`);
                    if (events_from_db[i].description !== null) {
                        $("#event-description").val(`${events_from_db[i].description}`);
                    }
                    $("#event-reminder").val(`${events_from_db[i].remind_before_day}`);
                    $("#event-id").val(`${events_from_db[i].id}`);
                    break;
                }
            }
            $("#CalenderModal").attr("class", "modal fade show");
            $("#CalenderModal").attr("style", "display: block; padding-right: 16px;");
            $(".btn-delete-modal").removeAttr("hidden");
            $("#event-created_by-form").removeAttr("hidden");

        }

    });
                        


    $(document).on("click", ".btn-add-event", function () {

        var today = new Date();
        var year = today.getFullYear();
        var month = today.getMonth() + 1;
        var day = today.getDate();

        month < 10 ? month=`0${month}` : month
        today = `${year}-${month}-${day}`;
        $("#event-date").attr('min', today);
        $("#event-date").val("");
        $("#event-reminder").val("7").change();
        
        $("#CalenderModal").attr("class", "modal fade show");
        $("#CalenderModal").attr("style", "display: block; padding-right: 16px;");

    });


    $(document).on("click", ".btn-close-modal", function () {
        $("#event-id").val("");
        $("#event-title").val("");
        $("#event-created_by").val("");
        $("#event-description").val("");
        $("#CalenderModal").attr("class", "modal fade");
        $("#CalenderModal").attr("style", "");
    });


    $(document).on("click", ".btn-save-modal", function () {
        $("#event-modal-form").submit();
    });


    $(document).on("click", ".btn-delete-modal", function () {
        var event_id = $("#event-id").val();
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                $.post('@Url.Action("Delete","Calendar")', { id: event_id }, function (data) {
                    if (data.result == "ok") {
                        Swal.fire({
                            //position: 'top-end',
                            icon: 'success',
                            title: 'Your event has been deleted.',
                            showConfirmButton: false,
                            timer: 2000
                        })
                        setTimeout(function () {
                            location.reload();
                        }, 2000);
                    } else {
                        Swal.fire({
                            //position: 'top-end',
                            type: 'error',
                            title: data.result,
                            showConfirmButton: false,
                            timer: 2000
                        })
                    }
                });
            }
        })

    });


</script>

}